CREATE TABLE IF NOT EXISTS ai_pending_action (
  action_id CHAR(32) PRIMARY KEY,
  user_id INT NOT NULL,
  agent_run_id BIGINT NULL,
  conversation_id BIGINT NULL,
  action_type VARCHAR(64) NOT NULL,
  required_permission VARCHAR(80) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_CONFIRMATION',
  payload_json MEDIUMTEXT NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  result_json MEDIUMTEXT NULL,
  summary VARCHAR(500) NOT NULL,
  page_context VARCHAR(100) NULL,
  request_id VARCHAR(80) NULL,
  expires_at DATETIME NOT NULL,
  confirmed_at DATETIME NULL,
  executed_at DATETIME NULL,
  error_message VARCHAR(500) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_pending_action_user FOREIGN KEY (user_id) REFERENCES t_user(user_id),
  CONSTRAINT fk_ai_pending_action_run FOREIGN KEY (agent_run_id) REFERENCES ai_agent_run(run_id),
  CONSTRAINT fk_ai_pending_action_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversation(conversation_id),
  INDEX idx_ai_pending_action_user_status (user_id, status, expires_at),
  INDEX idx_ai_pending_action_run (agent_run_id)
);
